### ISSUE TITLE
actualizar base 1er trimestre 2023

### ISSUE THREAD

**Issue by ClaraClari** [institutohumai/pyeph#2]
[EPH_usu_1_Trim_2023_txt.zip](https://github.com/institutohumai/pyeph/files/12316392/EPH_usu_1_Trim_2023_txt.zip)

**Comment by mpvaldez** [comment]
Gracias!
Ahi actualicé las bases de EPH con esta ultima entrega (2023T1). 

Perdón la demora

[Aquí está el repositorio con las bases para chusmear](https://github.com/reflejar/pyeph-data)
